### ISSUE TITLE
スクロールアニメーションを追加したい

### ISSUE THREAD

**Issue by Ran350** [Ran350/portfolio#8]
ヘッダーサブタイトルをクリックして各セクションまでスクロールさせたい
フッターにページトップまで戻るボタンを配置したい

**Comment by Ran350** [comment]
- ヘッダーサブタイトルをクリックして各セクションまでスクロールさせたい
- フッターにページトップまで戻るボタンを配置したい

**Comment by ygkn** [comment]
[`scroll-behavior`](https://developer.mozilla.org/ja/docs/Web/CSS/scroll-behavior) を使う手もあるらしい

**Comment by ygkn** [comment]
> 1. `yarn add @types/react-scroll` を実行
> 2. `import { Link } from "react-scroll"` で `Module not found: Can't resolve 'react-scroll'` と怒られてしまう cry

型定義だけしてパッケージ自体インストールしてないとか？

```sh
yarn add react-scroll
```

ためしてみてね
