### ISSUE TITLE
hover時アニメーションを変えたい

### ISSUE THREAD

**Issue by Ran350** [Ran350/portfolio#9]
- Button コンポーネントのアニメーションが，HeaderのSNSアイコンの流用実装なので変えたい

- スマホ，iPad画角でCardを指で触れたときに，影が広がっていくようなアニメーションやりたい
例： [Google Fonts](https://fonts.google.com/)

**Comment by ygkn** [comment]
[Material Design の Ripple](https://material-components.github.io/material-components-web-catalog/#/component/ripple) やね

「CSS Ripple effect」とかでググったら例が出てくると思われ
